# This mainly run
name: "Dotnet Initialize"
description: "Initializes dotnet environment for build, test and publish"

inputs:
  dotnetVersion:
    description: "specified dotnet version would be installed on the runner"
    required: false
    type: string
    default: "8.0.x"
  gitversionVersionSpec:
    description: "Version specification of gitversion"
    required: false
    type: string
    default: "5.x"

outputs:
  SemVer:
    description: "Semantic version from GitVersion"
    value: ${{ steps.gitversion.outputs.SemVer }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # required so GitVersion has full history

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: ${{ inputs.gitversionVersionSpec }}

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}
